"""check changes

Revision ID: ef4f518d317e
Revises: b92f2d023ce5
Create Date: 2026-02-23 19:22:53.630055

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef4f518d317e'
down_revision = 'b92f2d023ce5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('match', schema=None) as batch_op:
        batch_op.drop_column('resultat')

    with op.batch_alter_table('prediction', schema=None) as batch_op:
        batch_op.alter_column('resultatMatch',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prediction', schema=None) as batch_op:
        batch_op.alter_column('resultatMatch',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=False)

    with op.batch_alter_table('match', schema=None) as batch_op:
        batch_op.add_column(sa.Column('resultat', sa.VARCHAR(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
