"""added is_admin to individu

Revision ID: a554858484da
Revises: ef4f518d317e
Create Date: 2026-02-24 02:16:35.750505

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a554858484da'
down_revision = 'ef4f518d317e'
branch_labels = None
depends_on = None


def upgrade():
    # Add column with default False
    op.add_column('individu', sa.Column('is_admin', sa.Boolean(), nullable=False, server_default=sa.false()))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('individu', schema=None) as batch_op:
        batch_op.drop_column('isAdmin')

    # ### end Alembic commands ###
