"""Initial schema with tables

Revision ID: b92f2d023ce5
Revises: 
Create Date: 2026-02-19 02:05:24.292066

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b92f2d023ce5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('equipe',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('logo_url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('individu',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nomComplet', sa.String(), nullable=False),
    sa.Column('password', sa.String(length=60), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nomComplet')
    )
    op.create_table('match',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('equipeHomeId', sa.Integer(), nullable=False),
    sa.Column('equipeAwayId', sa.Integer(), nullable=False),
    sa.Column('stadeCompet', sa.String(), nullable=False),
    sa.Column('dateMatch', sa.DateTime(), nullable=True),
    sa.Column('resultat', sa.String(), nullable=True),
    sa.Column('scoreEquipe1', sa.Integer(), nullable=True),
    sa.Column('scoreEquipe2', sa.Integer(), nullable=True),
    sa.Column('coteEquipe1', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('coteEquipe2', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['equipeAwayId'], ['equipe.id'], ),
    sa.ForeignKeyConstraint(['equipeHomeId'], ['equipe.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('equipeHomeId', 'equipeAwayId', 'stadeCompet')
    )
    op.create_table('prediction',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('individu_id', sa.Integer(), nullable=False),
    sa.Column('idMatch', sa.Integer(), nullable=False),
    sa.Column('resultatMatch', sa.String(), nullable=False),
    sa.Column('scoreTeam1', sa.Integer(), nullable=False),
    sa.Column('scoreTeam2', sa.Integer(), nullable=False),
    sa.Column('winScore', sa.Boolean(), nullable=True),
    sa.Column('winOutcome', sa.Boolean(), nullable=True),
    sa.Column('autres', sa.String(), nullable=True),
    sa.Column('datePrediction', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['idMatch'], ['match.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['individu_id'], ['individu.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('individu_id', 'idMatch')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prediction')
    op.drop_table('match')
    op.drop_table('individu')
    op.drop_table('equipe')
    # ### end Alembic commands ###
