"""initial migration

Revision ID: f5077d4576aa
Revises: 
Create Date: 2026-02-14 15:31:03.897848

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5077d4576aa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('individu',
    sa.Column('nomComplet', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('nomComplet')
    )
    op.create_table('match',
    sa.Column('equipe1', sa.String(), nullable=False),
    sa.Column('equipe2', sa.String(), nullable=False),
    sa.Column('stadeCompet', sa.String(), nullable=False),
    sa.Column('dateMatch', sa.Date(), nullable=False),
    sa.Column('heureMatch', sa.Time(), nullable=False),
    sa.Column('resultat', sa.String(), nullable=False),
    sa.Column('scoreEquipe1', sa.Integer(), nullable=False),
    sa.Column('scoreEquipe2', sa.Integer(), nullable=False),
    sa.Column('coteEquipe1', sa.Integer(), nullable=False),
    sa.Column('coteEquipe2', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('equipe1', 'equipe2', 'stadeCompet')
    )
    op.create_table('prediction',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('individu_nomComplet', sa.String(), nullable=False),
    sa.Column('equipe1', sa.String(), nullable=False),
    sa.Column('equipe2', sa.String(), nullable=False),
    sa.Column('stadeCompet', sa.String(), nullable=False),
    sa.Column('resultat', sa.String(), nullable=False),
    sa.Column('scoreTeam1', sa.Integer(), nullable=False),
    sa.Column('scoreTeam2', sa.Integer(), nullable=False),
    sa.Column('win', sa.Integer(), nullable=False),
    sa.Column('autres', sa.String(), nullable=False),
    sa.Column('datePrediction', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['equipe1', 'equipe2', 'stadeCompet'], ['match.equipe1', 'match.equipe2', 'match.stadeCompet'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['individu_nomComplet'], ['individu.nomComplet'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('individu_nomComplet', 'equipe1', 'equipe2', 'stadeCompet')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prediction')
    op.drop_table('match')
    op.drop_table('individu')
    # ### end Alembic commands ###
